[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18.17.0"
  NEXT_TELEMETRY_DISABLED = "1"

# SPA routing - catch all and serve index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200