[build]
  command = "npm run build"
  publish = "out"

[context.production]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "22.11.0"
  NEXT_TELEMETRY_DISABLED = "1"

# Ensure static assets are properly served
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"