[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "22.11.0"
  NEXT_TELEMETRY_DISABLED = "1"

[context.production.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

# Force Next.js framework detection
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true